In [33]:
import numpy as np
import matplotlib.pyplot as plt


data = np.loadtxt(open("ex1data2.txt"),delimiter = ',')
#print(data)
X = np.array(data[:,0:2])
#X = np.c_[X,data[:,1]]
y = np.array(data[:,2])
y.shape = (len(y),1)
theta = np.zeros((3,1))
A = np.ones(len(y))
#size, bedrooms -> price


X = np.c_[A,X]

#print(X)
print(X)
print(y)
print(theta)
print("X = ", X.shape)
print("Theta = ",theta.shape)
print("y = ",y.shape)

[[1.000e+00 2.104e+03 3.000e+00]
 [1.000e+00 1.600e+03 3.000e+00]
 [1.000e+00 2.400e+03 3.000e+00]
 [1.000e+00 1.416e+03 2.000e+00]
 [1.000e+00 3.000e+03 4.000e+00]
 [1.000e+00 1.985e+03 4.000e+00]
 [1.000e+00 1.534e+03 3.000e+00]
 [1.000e+00 1.427e+03 3.000e+00]
 [1.000e+00 1.380e+03 3.000e+00]
 [1.000e+00 1.494e+03 3.000e+00]
 [1.000e+00 1.940e+03 4.000e+00]
 [1.000e+00 2.000e+03 3.000e+00]
 [1.000e+00 1.890e+03 3.000e+00]
 [1.000e+00 4.478e+03 5.000e+00]
 [1.000e+00 1.268e+03 3.000e+00]
 [1.000e+00 2.300e+03 4.000e+00]
 [1.000e+00 1.320e+03 2.000e+00]
 [1.000e+00 1.236e+03 3.000e+00]
 [1.000e+00 2.609e+03 4.000e+00]
 [1.000e+00 3.031e+03 4.000e+00]
 [1.000e+00 1.767e+03 3.000e+00]
 [1.000e+00 1.888e+03 2.000e+00]
 [1.000e+00 1.604e+03 3.000e+00]
 [1.000e+00 1.962e+03 4.000e+00]
 [1.000e+00 3.890e+03 3.000e+00]
 [1.000e+00 1.100e+03 3.000e+00]
 [1.000e+00 1.458e+03 3.000e+00]
 [1.000e+00 2.526e+03 3.000e+00]
 [1.000e+00 2.200e+03 3.000e+00]
 [1.000e+00 2.637e+03 3.000e+00]
 [1.000e+0

In [35]:
def computeCost(X,y,theta):
    m = len(y)
    J = 0
    new_arr = (np.dot(X,theta) - y)
    #print(new_arr)
    new_arr = np.square(new_arr)
    sq = np.sum(new_arr)
    J = sq * (1/(2*m))
    return J
    
def GradientDescent(X,y,theta,alpha,iterations):
    m = len(y)
    J_history = np.array([])
    for x in range(iterations):
        pred = np.dot(X,theta)
        delta = (1/m)*np.dot( (pred-y).transpose(),X).transpose()
        #print(delta.shape)
        theta = theta - alpha*delta
        newCost = computeCost(X,y,theta)
        J_history = np.append(J_history,newCost)
    print(theta)    
    return theta,J_history
    
alpha = 0.01
iterations = 400
cost = computeCost(X,y,theta)
print("Initial cost will zero thetas : ",cost)

theta,J_history = GradientDescent(X,y,theta,alpha,iterations)
print(theta)
#J_history.shape = (iterations,1)
#print(J_history)
#iterator = [x for x in range(1,iterations+1)]
#plt.plot(iterator,J_history)
#plt.xlabel("No of iterations")
#plt.ylabel("Value of cost fn")

Initial cost will zero thetas :  65591548106.45744
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]


/usr/lib/python3/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: overflow encountered in square
  
/usr/lib/python3/dist-packages/ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in subtract
